from django.conf.urls import patterns, url
from mueble import views
from mueble.views import MuebleListView, TamanoMuebleListView


urlpatterns = patterns('',
                       url(r'^mueble1/$', MuebleListView.as_view()),
                       url(r'^mueble2/$', TamanoMuebleListView.as_view()),
                       url(r'^$', views.lista_mueble, name='lista_mueble'),
                       url(r'^nuevo', views.add_mueble, name='add_mueble'),
                       url(r'^editar/(?P<pk>\d+)/$', views.edit_mueble,
                           name='edit_mueble'),
                       url(r'^buscar/(?P<idtipomueble>\d+)/$', views.buscar_mueble,
                           name='buscar_mueble'),
                       url(r'^tipo_mueble/$', views.lista_tipo_mueble,
                           name='lista_tipo_mueble'),
                       url(r'^tipo_mueble/nuevo', views.add_tipo_mueble,
                           name='add_tipo_mueble'),
                       url(r'^tipo_mueble/editar/(?P<pk>\d+)/$',
                           views.edit_tipo_mueble, name='edit_tipo_mueble'),
                       url(r'^forma_mueble/$', views.lista_forma_mueble,
                           name='lista_forma_mueble'),
                       url(r'^forma_mueble/nuevo', views.add_formamueble,
                           name='add_formamueble'),
                       url(r'^forma_mueble/editar/(?P<pk>\d+)/$',
                           views.edit_forma_mueble, name='edit_forma_mueble'),
                       url(r'^ocupacion/$', views.lista_ocupacion,
                           name='lista_ocupacion'),
                       url(r'^ocupacion/nuevo', views.add_ocupacion,
                           name='add_ocupacion'),
                       url(r'^ocupacion/editar/(?P<pk>\d+)/$',
                           views.edit_ocupacion, name='edit_ocupacion'),
                       url(r'^tamano/$', views.lista_tamano,
                           name='lista_tamano'),
                       url(r'^tamano/nuevo', views.add_tamano,
                           name='add_tamano'),
                       url(r'^tamano/editar/(?P<pk>\d+)/$',
                           views.edit_tamano, name='edit_tamano'),
                       url(r'^tamano_mueble/(?P<idmueble>\d+)/$', views.buscar_tamano_mueble,
                           name='buscar_tamano_mueble'),
                       url(r'^tamano_mueble/nuevo', views.add_tamanomueble,
                           name='add_tamanomueble'),
                       url(r'^tamano_mueble/editar/(?P<pk>\d+)/$',
                           views.edit_tamanomueble, name='edit_tamanomueble'),
                       url(r'^mueble_ambiente/(?P<idambiente>\d+)/$',
                           views.buscar_mueble_ambiente,
                           name='buscar_mueble_ambiente'),
                       url(r'^mueble_ambiente/nuevo', views.add_muebleambiente,
                           name='add_muebleambiente'),
                       url(r'^mueble_ambiente/editar/(?P<pk>\d+)/$',
                           views.edit_muebleambiente, name='edit_muebleambiente'),
                       )
