# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
        ('servicio', '0002_auto_20150515_1212'),
        ('direccion', '0003_auto_20150515_1210'),
        ('contenido', '0003_auto_20150518_1426'),
        ('mueble', '0001_initial'),
        ('cliente', '0003_auto_20150515_1210'),
        ('trabajador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('numero_contrato', models.CharField(max_length=100)),
                ('numero_cotizacion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField()),
                ('fecha_estimadamudanza', models.DateTimeField()),
                ('cantidad_ambientes', models.IntegerField()),
                ('cantidad_muebles', models.IntegerField()),
                ('volumen_muebles_sugerido', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_muebles_cotizado', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso_muebles', models.DecimalField(max_digits=5, decimal_places=2)),
                ('cantidad_contenedores', models.IntegerField()),
                ('peso_contenedores', models.DecimalField(max_digits=7, decimal_places=2)),
                ('volumen_contenedores', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_contenidos', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_contenidos', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso_materiales', models.DecimalField(max_digits=5, decimal_places=2)),
                ('monto_muebles', models.DecimalField(max_digits=7, decimal_places=2)),
                ('monto_material', models.DecimalField(max_digits=7, decimal_places=2)),
                ('monto_descuento', models.DecimalField(max_digits=7, decimal_places=2)),
                ('total_sin_impuesto', models.DecimalField(max_digits=7, decimal_places=2)),
                ('monto_impuesto', models.DecimalField(max_digits=7, decimal_places=2)),
                ('total_con_impuesto', models.DecimalField(max_digits=7, decimal_places=2)),
                ('tiempo_carga', models.TimeField()),
                ('total_recorrido_tiempo', models.TimeField()),
                ('total_recorrido_km', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('cotizador', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='cotizador')),
                ('creadopor', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='creadopor')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
                'verbose_name': 'Cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Ambiente',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('cantidad_muebles', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_muebles', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_muebles', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cantidad_contenedores', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_contenedores', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_contenedores', models.DecimalField(max_digits=7, decimal_places=2)),
                ('volumen_contenidos', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_contenidos', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_materiales', models.DecimalField(max_digits=7, decimal_places=2)),
                ('observaciones', models.TextField(blank=True)),
                ('ambiente', models.ForeignKey(to='ambiente.Ambiente')),
                ('cotizacion', models.ForeignKey(to='cotizacion.Cotizacion')),
            ],
            options={
                'verbose_name_plural': 'Ambientes de la cotizacion',
                'verbose_name': 'Ambiente de la cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Contenedor',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('capacidad_volumen_contenedor', models.DecimalField(max_digits=5, decimal_places=2)),
                ('capacidad_peso_contenedor', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_contenedor', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso_contenedor', models.DecimalField(max_digits=5, decimal_places=2)),
                ('retornable', models.BooleanField(default=None)),
                ('contenedor', models.ForeignKey(to='contenido.Contenedor')),
            ],
            options={
                'verbose_name_plural': 'contenedores de la cotizacion',
                'verbose_name': 'contenedor de la cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('densidad', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen_contenido', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso_contenido', models.DecimalField(max_digits=5, decimal_places=2)),
                ('porcentaje', models.DecimalField(max_digits=2, decimal_places=2)),
                ('contenido', models.ForeignKey(to='contenido.Contenido')),
                ('cotizacion_contenedor', models.ForeignKey(to='cotizacion.Cotizacion_Contenedor')),
            ],
            options={
                'verbose_name_plural': 'contenidos en el contenedor',
                'verbose_name': 'contenido en el contenedor',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('direccion', models.CharField(max_length=550)),
                ('tipo_direccion', models.CharField(max_length=100)),
                ('cotizacion', models.ForeignKey(to='cotizacion.Cotizacion')),
            ],
            options={
                'verbose_name_plural': 'direcciones de la cotizacion',
                'verbose_name': 'direccion de la cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Material',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('cantidad', models.DecimalField(max_digits=5, decimal_places=2)),
                ('precio_unitario', models.DecimalField(max_digits=7, decimal_places=2)),
                ('precio_total', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_unitario', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso_total', models.DecimalField(max_digits=5, decimal_places=2)),
                ('recuperable', models.BooleanField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Materiales del mueble',
                'verbose_name': 'Material del mueble',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Mueble',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('tamano', models.CharField(max_length=100)),
                ('ancho', models.DecimalField(max_digits=5, decimal_places=2)),
                ('alto', models.DecimalField(max_digits=5, decimal_places=2)),
                ('largo', models.DecimalField(max_digits=5, decimal_places=2)),
                ('volumen', models.DecimalField(max_digits=7, decimal_places=2)),
                ('capacidad', models.DecimalField(max_digits=5, decimal_places=2)),
                ('ocupacion', models.DecimalField(max_digits=2, decimal_places=2)),
                ('forma', models.CharField(max_length=100)),
                ('trasladable', models.BooleanField(default=None)),
                ('apilable', models.BooleanField(default=None)),
                ('capacidad_carga', models.BooleanField(default=None)),
                ('capacidad_interna', models.BooleanField(default=None)),
                ('observaciones', models.TextField()),
                ('cotizacion_ambiente', models.ForeignKey(to='cotizacion.Cotizacion_Ambiente')),
                ('mueble', models.ForeignKey(to='mueble.Mueble')),
            ],
            options={
                'verbose_name_plural': 'Muebles del Ambiente',
                'verbose_name': 'Mueble del Ambiente',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('cotizacion_mueble', models.ForeignKey(to='cotizacion.Cotizacion_Mueble')),
                ('servicio', models.ForeignKey(to='servicio.Servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios del mueble',
                'verbose_name': 'Servicio del mueble',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cotizacion_trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('tarifa', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cantidad', models.IntegerField()),
                ('total_sin_recargo', models.DecimalField(max_digits=7, decimal_places=2)),
                ('nocturno', models.BooleanField(default=None)),
                ('fin_semana', models.BooleanField(default=None)),
                ('recargo_nocturno', models.DecimalField(max_digits=7, decimal_places=2)),
                ('recargo_fin_semana', models.DecimalField(max_digits=7, decimal_places=2)),
                ('total_con_recargo', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cargo', models.ForeignKey(to='trabajador.Cargo_trabajador')),
                ('cotizacion', models.ForeignKey(to='cotizacion.Cotizacion')),
            ],
            options={
                'verbose_name_plural': 'trabajadores de la cotizacion',
                'verbose_name': 'trabajador de la cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Estado_Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'estados',
                'verbose_name': 'estado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('piso', models.CharField(max_length=100)),
                ('factor', models.DecimalField(max_digits=3, decimal_places=2)),
            ],
            options={
                'verbose_name_plural': 'pisos',
                'verbose_name': 'piso',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tiempo_Carga',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('tiempo_carga', models.TimeField()),
                ('volumen_min', models.DecimalField(max_digits=13, decimal_places=2)),
                ('volumen_max', models.DecimalField(max_digits=13, decimal_places=2)),
                ('nro_objeto_min', models.IntegerField()),
                ('nro_objeto_max', models.IntegerField()),
                ('peso_min', models.DecimalField(max_digits=13, decimal_places=2)),
                ('peso_max', models.DecimalField(max_digits=13, decimal_places=2)),
            ],
            options={
                'verbose_name_plural': 'tiempos de carga',
                'verbose_name': 'tiempo de carga',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('modelo', models.CharField(max_length=100)),
                ('tarifa_hora', models.DecimalField(max_digits=7, decimal_places=2)),
                ('tarifa_recorrido', models.DecimalField(max_digits=7, decimal_places=2)),
                ('capacidad_volumen', models.DecimalField(max_digits=7, decimal_places=2)),
                ('capacidad_peso', models.DecimalField(max_digits=7, decimal_places=2)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'verbose_name': 'Vehiculo',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Vehiculo_Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('cantidad', models.IntegerField()),
                ('cantidad_hora', models.TimeField()),
                ('tarifa_hora', models.DecimalField(max_digits=7, decimal_places=2)),
                ('costo_hora', models.DecimalField(max_digits=7, decimal_places=2)),
                ('recorrido', models.DecimalField(max_digits=7, decimal_places=2)),
                ('tarifa_recorrido', models.DecimalField(max_digits=7, decimal_places=2)),
                ('costo_recorrido', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cotizacion', models.ForeignKey(to='cotizacion.Cotizacion')),
                ('vehiculo', models.ForeignKey(to='cotizacion.Vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos de la cotizacion',
                'verbose_name': 'Vehiculo de la cotizacion',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='cotizacion_material',
            name='cotizacion_mueble',
            field=models.ForeignKey(to='cotizacion.Cotizacion_Mueble'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cotizacion_material',
            name='material',
            field=models.ForeignKey(to='servicio.Material'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cotizacion_contenedor',
            name='cotizacion_mueble',
            field=models.ForeignKey(to='cotizacion.Cotizacion_Mueble'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cotizacion_ambiente',
            name='piso',
            field=models.ForeignKey(to='cotizacion.Piso'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.ForeignKey(to='cotizacion.Estado_Cotizacion'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direccion.Inmueble'),
            preserve_default=True,
        ),
    ]
